packages:
  - apps/*
  - packages/*
  - configs/*
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
# nodeLinker: hoisted
hoistPattern:
  - "!electron"
publicHoistPattern:
  - "!electron"
loglevel: debug
