packages:
  - apps/*
  - packages/*
  - configs/*
hoistPattern:
  - '!electron'
loglevel: debug
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - electron
  - electron-winstaller
  - esbuild
  - prisma
  - zenstack
publicHoistPattern:
  - '!electron'
